import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { SearchProvider } from "./components/SearchProvider";
import { FilterProvider, SortProvider } from "./components/FilterProvider";
import Filter from "./components/Filter";
import Sort from "./components/Sort";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <SearchProvider>
        <FilterProvider>
          <SortProvider>
      <body>
      <Header/>
      <div className="flex">
      <Filter/>
      <Sort className='m-2'/>
      </div>
        {children}
      </body>
      </SortProvider>
      </FilterProvider>
      </SearchProvider>
    </html>
  );
}


