import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { SearchProvider } from "./components/SearchProvider";
import { FilterProvider, SortProvider } from "./components/FilterProvider";
import Filter from "./components/Filter";
import Sort from "./components/Sort";
import { Suspense } from "react";
import { AuthProvider } from "./Authcontext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body>
        <AuthProvider>
       <SearchProvider>
        <FilterProvider>
          <SortProvider>
      <Header/>
      <Suspense>
        {children}
      </Suspense>
      </SortProvider>
      </FilterProvider>
      </SearchProvider>
      </AuthProvider>
      </body>
    </html>
  );
}


